FROM amd64/debian:buster-slim
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get clean

ADD https://builds.parsecgaming.com/package/parsec-linux.deb /root/parsec-linux.deb

WORKDIR /root/
RUN dpkg -i parsec-linux.deb && rm parsec-linux.deb

RUN mkdir -p /root/.parsec && \
echo "encoder_h265 = 1" > /root/.parsec/config.txt
