FROM --platform=linux/amd64 debian:buster-slim
ENV DEBIAN_FRONTEND noninteractive
COPY qemu-x86_64-static /usr/bin

RUN apt-get update && \
apt-get -y install libgl1-mesa-glx libgl1 libsm6 libx11-6 libxxf86vm1 && \
apt-get clean

ADD https://builds.parsecgaming.com/package/parsec-linux.deb /root/parsec-linux.deb

WORKDIR /root/
RUN dpkg -i parsec-linux.deb && rm parsec-linux.deb

RUN mkdir -p /root/.parsec && \
echo "encoder_h265 = 1" > /root/.parsec/config.txt
